[windows]
winvm ansible_host=192.168.29.33

[windows:vars]
ansible_connection=winrm
ansible_port=5986
ansible_winrm_transport=certificate
ansible_winrm_cert_pem=D:\projects\T3\cert.pem
ansible_winrm_cert_key_pem=D:\projects\T3\key.pem
ansible_winrm_server_cert_validation=ignore